server.port=8082
spring.application.name=length-service

spring.datasource.url=jdbc:mysql://localhost:3306/length_service_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=manish
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Auth service base URL for token validation
auth.service.url=http://localhost:8081

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
